name: RhysC
favicon: null
layout_spectrum: 0.536781266797334
typography_spectrum: 0.25355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 1
  lightness: 0.43819636665284634
  saturation: 0.2582776846829802
  rhythmicContrast: 0.49472027481533587
purpose: []
